In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])



In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [12]:
dframe1

X         Y         Z
0  1.167847 -1.275692 -1.532982
1  1.237811  1.201194 -0.184550
2 -0.524974 -0.566826  0.144694
3 -0.309258  0.359590  1.393656

In [13]:
dframe2

Y         Q         X
0  0.015998 -0.261294 -1.834770
1 -0.056601 -0.537070  1.417575
2 -0.861622 -0.749430  1.518211

In [14]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0  1.167847 -1.275692 -1.532982       NaN
1  1.237811  1.201194 -0.184550       NaN
2 -0.524974 -0.566826  0.144694       NaN
3 -0.309258  0.359590  1.393656       NaN
0 -1.834770  0.015998       NaN -0.261294
1  1.417575 -0.056601       NaN -0.537070
2  1.518211 -0.861622       NaN -0.749430

In [15]:
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0  1.167847 -1.275692 -1.532982       NaN
1  1.237811  1.201194 -0.184550       NaN
2 -0.524974 -0.566826  0.144694       NaN
3 -0.309258  0.359590  1.393656       NaN
4 -1.834770  0.015998       NaN -0.261294
5  1.417575 -0.056601       NaN -0.537070
6  1.518211 -0.861622       NaN -0.749430