In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
dframe = DataFrame(np.arange(16).reshape(4,4))

In [3]:
blender = np.random.permutation(4)

In [4]:
blender

array([0, 2, 3, 1])

In [5]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
dframe.take(blender)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [7]:
box = np.array([1,2,3])

In [9]:
shaker = np.random.randint(0,len(box),size=10)  # randint is a permutaiton with replacement 
                                                #(low,high,how many times)

In [10]:
shaker

array([0, 0, 0, 1, 1, 0, 0, 2, 0, 0])

In [11]:
hand_grabs = box.take(shaker)

hand_grabs

array([1, 1, 1, 2, 2, 1, 1, 3, 1, 1])