In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]


In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list1,my_list2]

In [7]:
my_array2 = np.array(my_lists)

In [9]:
my_array2   #multi dimensional array

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
my_array2.shape # it is a 2 x 4

(2, 4)

In [13]:
my_array2.dtype # tells me about the type of objects in that array

dtype('int64')

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
my_zeros_array = np.zeros(5)

In [16]:
my_zeros_array.dtype

dtype('float64')

In [17]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.empty(5)  # something weird is happening here. Need to invsetigate. It should return array([0.,0.,0.,0.,0.,])

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])