In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 0.01785217, -0.68014102,  0.28492394, -0.27006233, -0.72493362,
        0.14899883,  0.69771879,  0.60188391,  0.1892482 ,  0.56142314])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-0.68015578,  0.46073881,  1.11742221, -0.56083041,  0.33067715,
       -1.99883685,  0.33723058,  1.44827414,  0.40788415, -1.28545989])

In [10]:
# Binary Functions
np.add(A,B)

array([-0.66230361, -0.21940221,  1.40234615, -0.83089274, -0.39425647,
       -1.84983801,  1.03494936,  2.05015805,  0.59713235, -0.72403674])

In [12]:
np.maximum(A,B) #compares values at each index and returns the max

array([ 0.01785217,  0.46073881,  1.11742221, -0.27006233,  0.33067715,
        0.14899883,  0.69771879,  1.44827414,  0.40788415,  0.56142314])

In [13]:
website = 'https://numpy.org/doc/1.26/user/basics.ufuncs.html'
import webbrowser
webbrowser.open(website)

True