In [1]:
import numpy as np

In [3]:
arr = np.arange(5)

In [4]:
arr

array([0, 1, 2, 3, 4])

In [5]:
np.save('myarray',arr)

In [6]:
arr = np.arange(10)

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [10]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [11]:
arr2 = arr

In [12]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [14]:
archive_array = np.load('ziparray.npz')

In [15]:
archive_array

In [16]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [17]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr = np.array([[1,2,3],[4,5,6]])

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [22]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')

In [23]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])