In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10)  #ten evenly spaced points between 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(4) # good for linear algebra problems

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.20480866, 0.4442155 , 0.67222155, 0.7427306 , 0.83765145])

In [18]:
np.random.rand(5,5)

array([[0.05654472, 0.54817269, 0.80841995, 0.63966626, 0.35243221],
       [0.63765259, 0.06398883, 0.37806578, 0.2622641 , 0.61844816],
       [0.03123067, 0.61832567, 0.96103506, 0.80656552, 0.78031154],
       [0.47244492, 0.42300569, 0.4733379 , 0.91331543, 0.97739437],
       [0.88397304, 0.44496645, 0.29620166, 0.68051266, 0.24989958]])

In [19]:
np.random.randn(2) 

array([ 0.36609615, -1.14653769])

In [20]:
np.random.randint(1,100) 

25

In [21]:
np.random.randint(1,100,10) 

array([17, 15, 40, 64, 60, 74, 89, 29, 68, 91])

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0,50,10)

In [25]:
ranarr

array([ 0, 17, 14, 26, 18, 22, 11, 10, 47, 36])

In [27]:
arr.reshape(5,5) # you need enough elements to fill up your new array or it will throw an error. 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr.max()

47

In [29]:
ranarr.min()

0

In [30]:
ranarr.argmax() # the max value is located the the index 8

8

In [31]:
ranarr.argmin()

0

In [33]:
arr.shape

(25,)

In [34]:
arr = arr.reshape(5,5)

In [36]:
arr.shape

(5, 5)

In [38]:
arr.dtype # returns the data type from the arr

dtype('int64')

In [39]:
from numpy.random import randint

In [40]:
randint(2,10)

4

In [41]:
arr = np.arange(0,11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[8] # returns the value at index 8

8

In [45]:
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [47]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [48]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[0:5] = 100

In [50]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
slice_of_arr = arr[0:6]

In [54]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [55]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [56]:
slice_of_arr[:] = 99

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [59]:
arr # when using slice it will also change the original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
# you have to copy the array first
arr_copy = arr.copy()

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
arr_copy[:] = 100

In [64]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d[0][0]   #[row][column]

5

In [70]:
arr_2d[0] # returns whole row

array([ 5, 10, 15])

In [72]:
arr_2d[2][1]  #double bracket notation

40

In [74]:
arr_2d[1,2] # single bracket notation

30

In [76]:
arr_2d[:2,1:]  #grab everything up to row 2 and grab every from column 1 onwards

array([[10, 15],
       [25, 30]])

In [77]:
arr = np.arange(1,11)

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
bool_arr = arr > 5

In [81]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [83]:
arr[bool_arr] # returns where boolean is True

array([ 6,  7,  8,  9, 10])

In [84]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [85]:
arr[arr<3]

array([1, 2])

In [86]:
arr_2d = np.arange(50).reshape(5,10)

In [87]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [89]:
arr = np.arange(0,11)

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [92]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [94]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [95]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [96]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [98]:
arr / arr

/var/folders/_7/178775hs6nz5h81l3b_pbb8h0000gn/T/ipykernel_13981/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [99]:
1/arr

/var/folders/_7/178775hs6nz5h81l3b_pbb8h0000gn/T/ipykernel_13981/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [100]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [101]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [102]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [103]:
np.max(arr)

10

In [104]:
arr.max()

10

In [105]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [106]:
np.log(arr)

/var/folders/_7/178775hs6nz5h81l3b_pbb8h0000gn/T/ipykernel_13981/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])